name: CI/CD DevOps App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Listar arquivos do projeto
        run: ls -la && ls -la app

      - name: Build da imagem Docker
        run: docker build -f docker/Dockerfile -t devops-app .

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: NOME_DO_SEU_APP
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./app
