name: Build and deploy site to Azure Web App - kalebe-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Upload artifact para deploy
        uses: actions/upload-artifact@v4
        with:
          name: app-site
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact do build
        uses: actions/download-artifact@v4
        with:
          name: app-site
          path: .

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_91CA0E270DEC4330BB967A126B0C4BA0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8FB20BC7B1B74E028F1C2A8659C4D948 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F4A91DEB639C48EF9886B8F36C1BEB26 }}

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kalebe-webapp'
          slot-name: 'Production'
          package: .
